[project]
name = "secondhanded-strollers-predictedprice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.2.6",
    "pandas>=2.3.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
